name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Installing dependencies
        run: npm i
      - name: Building React
        run: npm run build
      - name: Deploy to server
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.server762694.nazwa.pl
          username: server762694_github.action
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
